### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kevinrenskers** [invisibleroads/imapIO#1]
As soon as I try to import imapIO, I get the following error:

```
>>> import imapIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/renskers/Workspace/Planbord/lib/python2.6/site-packages/imapIO/__init__.py", line 84
    includes = {clean_tag(x) for x in includes} if includes else set()
                           ^
SyntaxError: invalid syntax
```

**Comment by invisibleroads** [comment]
Thank you for reporting this issue.

I am guessing that you are using an earlier version of Python.  The set literal syntax {1, 2, 3} was introduced in Python 2.7
http://docs.python.org/dev/whatsnew/2.7.html

Nevertheless, I reverted to the more standard set() syntax to fix your issue.  Hope that helps.
